CREATE PROCEDURE SP_DarDeBajaUsuario(@Usuario BIGINT)
AS 
BEGIN
BEGIN TRY 
IF (@Usuario IS NULL)
BEGIN
RAISERROR('No se ingreso un usuario', 16, 1)
RETURN
END
IF NOT EXISTS(SELECT 1 FROM UsuarioSistema WHERE idUsuario = @Usuario)
BEGIN
RAISERROR('El usuario ingresado no existe', 16, 1)
RETURN
END
BEGIN TRANSACTION
UPDATE UsuarioSistema SET Estado = 0 WHERE idUsuario = @Usuario
COMMIT TRANSACTION
END TRY
BEGIN CATCH
ROLLBACK TRANSACTION
DECLARE @Mensaje VARCHAR(500) = ERROR_MESSAGE()
DECLARE @Severidad INT = ERROR_SEVERITY()
DECLARE @EstadoError INT = ERROR_STATE()
RAISERROR(@Mensaje, @Severidad, @EstadoError)
END CATCH
END
